project_id: "6"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
base_url: "https://solana.crowdin.com"
preserve_hierarchy: true
files: [
    # Docs Markdown files
    {
      source: "/docs/**/*.*",
      translation: "/i18n/%two_letters_code%/docs/**/%original_file_name%",
      ignore: [
          # ignore all json and txt files in the docs dir
          "**/*.json",
          "**/*.txt",
        ],
    },
  ]
